language: python
python:
  - "3.6.0"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script: 
  - pytest --cov=api/test_api
after-success:
  - coveralls